// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO5t2t58SqCdCWz0I9x7Ueaitbf2JksZo',
    appId: '1:735731115556:web:5f1cf9add6817dd6fc1ab1',
    messagingSenderId: '735731115556',
    projectId: 'quizdeck-417c9',
    authDomain: 'quizdeck-417c9.firebaseapp.com',
    storageBucket: 'quizdeck-417c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3on7Uhgiethf5gU9XVBiTucqLGZnNjZQ',
    appId: '1:735731115556:android:d1301a32586347e7fc1ab1',
    messagingSenderId: '735731115556',
    projectId: 'quizdeck-417c9',
    storageBucket: 'quizdeck-417c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTjUrgSnoqx2SenA_JYqZtUW2hTrX2T3c',
    appId: '1:735731115556:ios:6f1e28b46e251cd7fc1ab1',
    messagingSenderId: '735731115556',
    projectId: 'quizdeck-417c9',
    storageBucket: 'quizdeck-417c9.firebasestorage.app',
    iosBundleId: 'com.quizdeck.quizdeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTjUrgSnoqx2SenA_JYqZtUW2hTrX2T3c',
    appId: '1:735731115556:ios:6f1e28b46e251cd7fc1ab1',
    messagingSenderId: '735731115556',
    projectId: 'quizdeck-417c9',
    storageBucket: 'quizdeck-417c9.firebasestorage.app',
    iosBundleId: 'com.quizdeck.quizdeck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO5t2t58SqCdCWz0I9x7Ueaitbf2JksZo',
    appId: '1:735731115556:web:b59f1271f840a861fc1ab1',
    messagingSenderId: '735731115556',
    projectId: 'quizdeck-417c9',
    authDomain: 'quizdeck-417c9.firebaseapp.com',
    storageBucket: 'quizdeck-417c9.firebasestorage.app',
  );
}
